name: C++ Build and Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make libgtest-dev libspdlog-dev

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build --target all
      working-directory: ${{github.workspace}}

    - name: Run tests
      run: cmake --build build --target test
      working-directory: ${{github.workspace}}

